config/routes.rb
Twocents::Application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :authentications, only: :create
      resources :users, only: [:index, :show, :create, :update, :destroy]
      resources :photos, only: [:index, :show, :update, :destroy]
      resources :collections, only: [:index, :show, :create, :update, :destroy] do
        resources :photos, only: [:index, :create]
      end
      resources :followers, only: [:index, :create, :destroy] do
        member do
          get 'accept'
          get 'block'
          get 'ignore'
          get 'decline'
        end
        collection do
          get 'pending'
          get 'ignored'
          get 'blocked'
        end
      end
      match '/following', to: 'followers#following'
    end
  end

  scope module: :web do
    resources :sessions, only: [:create, :destroy, :new]

    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

    match '/help',    to: 'pages#help'
    match '/about',   to: 'pages#about'
    match '/contact', to: 'pages#contact'

    root to: 'pages#home'
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :collection
  delegate :user, to: :collection, allow_nil: true

  extend FriendlyId
  friendly_id :caption, use: :slugged
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  acts_as_votable
  acts_as_commentable

  validates :caption, length: { maximum: 30 }


  def favourite_by(user)
    if collection.has_favourite_from_user? user
      collection.update_user_favourite user, self
    else
      collection.add_favourite_from_user user, self
    end
  end

  def unfavourite_by(user)
    collection.remove_favourite_for_user(user) if collection.favourite_of(user) == self
  end
end

app/controllers/api/v1/photos_controller.rb
class Api::V1::PhotosController < ApiController

  before_filter :find_photo, only: [:show, :update, :destroy]

  def index
    if params[:collection_id]
      @photos = collection.photos.take(25)
    else
      @photos = current_user.photos.take(25)
    end

    respond_with @photos
  end

  def show
    respond_with @photo
  end

  def create
    @photo = collection.photos.build photo_params

    if @photo.save
      respond_with @photo, status: :created, location: @photo
    else
      respond_with { errors: @photo.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    if @photo.update_attributes photo_params
      head :no_content
    else
      respond_with { errors: @photo.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @photo.destroy

    head :no_content
  end

  private

  def find_photo
    @photo = current_user.photos.find params[:id]
  end

  def collection
    current_user.collections.find params[:collection_id]
  end

  def photo_params
    params.require(:photo).permit(:caption, :image, :location)
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/web/photos/_form.html.haml
= form_for [@photo.user, @photo.collection, @photo] do |f|
  = render 'shared/errors', object: @photo
  .field
    = f.label :caption
    = f.text_field :caption
  .actions
    = f.submit

app/views/web/photos/edit.html.haml
%h1 Editing photo
= render 'form'
%ul
  %li= link_to 'Show', [@photo.user, @photo.collection, @photo]
  %li= link_to 'Back', user_collection_photos_path(@photo.user, @photo.collection)

app/views/web/photos/index.html.haml
%h1 Listing photos
%table
  %tr
    %th Photo
    %th
    %th
    %th
  - @photos.each do |photo|
    %tr
      %td= photo.caption
      %td= link_to 'Show', [photo.user, @collection, photo]
      %td= link_to 'Edit', edit_user_collection_photo_path(photo.user, @collection, photo)
      %td= link_to 'Destroy', [photo.user, @collection, photo], method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'New Photo', new_user_collection_photo_path(@collection.user, @collection)

app/views/web/photos/new.html.haml
%h1 New photo
= render 'form'
= link_to 'Back', user_collection_photos_path(@collection.user, @collection)

app/views/web/photos/show.html.haml
#notice= notice
%p
  %label User:
  = @photo.user.name
%p
  %label Collection:
  = @photo.collection.name
%p
  %label Photo:
  = @photo.caption
%ul
  %li= link_to 'Edit', edit_user_collection_photo_path(@photo.user, @photo.collection, @photo)
  %li= link_to 'Back', user_collection_photos_path(@photo.user, @photo.collection)