config/routes.rb
Twocents::Application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :authentications, only: :create
      resources :users, only: [:index, :show, :create, :update, :destroy]
      resources :photos, only: [:index, :show, :update, :destroy]
      resources :collections, only: [:index, :show, :create, :update, :destroy] do
        resources :photos, only: [:index, :create]
      end
      resources :followers, only: [:index, :create, :destroy] do
        member do
          get 'accept'
          get 'block'
          get 'ignore'
          get 'decline'
        end
        collection do
          get 'pending'
          get 'ignored'
          get 'blocked'
        end
      end
      match '/following', to: 'followers#following'
    end
  end

  scope module: :web do
    resources :sessions, only: [:create, :destroy, :new]

    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

    match '/help',    to: 'pages#help'
    match '/about',   to: 'pages#about'
    match '/contact', to: 'pages#contact'

    root to: 'pages#home'
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base

  belongs_to :user
  has_many :photos

  extend FriendlyId
  friendly_id :name, use: :slugged
  acts_as_commentable

  validates :name, presence: true,
                   length: { maximum: 50 }
  validates :description, length: { maximum: 500 }


  def has_favourite_for_user?(user)
    Favourite.find_by_user_id_and_collection_id(user.id, self.id).present? rescue false
  end

  def favourite_of(user)
    Favourite.find_by_user_id_and_collection_id(user.id, self.id)
  end

  def remove_favourite_for_user(user)
    Favourite.find_by_user_id_and_collection_id(user.id, self.id).try(:destroy) rescue nil
  end

  def update_user_favourite(user, photo)
    favourite = Favourite.find_by_user_id_and_collection_id user.id, self.id
    return false unless favourite
    favourite.photo = photo
    favourite.save
  end

  def add_favourite_from_user(user, photo)
    favourite = Favourite.new({collection: self, user: user, photo: photo})
    favourite.save
  end
end

app/controllers/api/v1/collections_controller.rb
class Api::V1::CollectionsController < ApiController

  before_filter :find_collection, only: [:show, :update, :destroy]

  def index
    @collections = current_user.collections.take 25

    respond_with @collections
  end

  def show
    respond_with @collection
  end

  def create
    @collection = @user.collections.build collection_params

    if @collection.save
      redirect_to api_v2_collection_path(@collection)
    else
      respond_with { errors: @collection.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    if @collection.update_attributes(collection_params)
      head :no_content
    else
      respond_with { errors: @collection.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @collection.destroy

    head :no_content
  end

  private

  def find_collection
    @collection = current_user.collections.find params[:id]
  end

  def collection_params
    params.require(:collection).permit(:name, :description)
  end

end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/web/collections/_form.html.haml
= form_for [@collection.user, @collection] do |f|
  = render 'shared/errors', object: @collection
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit

app/views/web/collections/edit.html.haml
%h1 Editing collection
= render 'form'
%ul
  %li= link_to 'Show', [@collection.user, @collection]
  %li= link_to 'Back', user_collections_path(@collection.user)

app/views/web/collections/index.html.haml
%h1 Listing collections
%table
  %tr
    %th Collection
    %th
    %th
    %th
  - @collections.each do |collection|
    %tr
      %td= collection.name
      %td= link_to 'Show', [@user, collection]
      %td= link_to 'Edit', edit_user_collection_path(@user, collection)
      %td= link_to 'Destroy', [@user, collection], method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'New Collection', new_user_collection_path(@user)

app/views/web/collections/new.html.haml
%h1 New collection
= render 'form'
= link_to 'Back', user_collections_path(@collection.user)

app/views/web/collections/show.html.haml
#notice= notice
%p
  %label User:
  = @collection.user.name
%p
  %label Collection:
  = @collection.name
%ul
  %li= link_to 'Edit', edit_user_collection_path(@collection.user, @collection)
  %li= link_to 'Back', user_collections_path(@collection.user)