config/routes.rb
Twocents::Application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :authentications, only: :create
      resources :users, only: [:index, :show, :create, :update, :destroy]
      resources :photos, only: [:index, :show, :update, :destroy]
      resources :collections, only: [:index, :show, :create, :update, :destroy] do
        resources :photos, only: [:index, :create]
      end
      resources :followers, only: [:index, :create, :destroy] do
        member do
          get 'accept'
          get 'block'
          get 'ignore'
          get 'decline'
        end
        collection do
          get 'pending'
          get 'ignored'
          get 'blocked'
        end
      end
      match '/following', to: 'followers#following'
    end
  end

  scope module: :web do
    resources :sessions, only: [:create, :destroy, :new]

    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

    match '/help',    to: 'pages#help'
    match '/about',   to: 'pages#about'
    match '/contact', to: 'pages#contact'

    root to: 'pages#home'
  end

end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    %small A Dos Centavos Creation
    %nav
      %ul
        %li= link_to "About",   about_path
        %li= link_to "Contact", contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "PicOne", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          %li= link_to "Help", help_path
          - if signed_in?
            %li= link_to "Users", users_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{href: "#", 'data-toggle' => 'dropdown'}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile",  current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li= link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title yield(:title)
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    / [if lt IE 9]
      %script{src: "http://html5shim.googlecode.com/svn/trunk/html5.js"}
  %body
    = render 'layouts/header'
    .container-fluid{ class: "#{params[:controller].split('/').last} #{params[:action]}" }
      - flash.each do |key,value|
        .div{class: "alert alert-#{key}"}= value
      = yield
    = render 'layouts/footer'
    - if Rails.env.development?
      .container= debug params